/**
 * Tailwind v4 `@theme` bridge (ADR-0009 §consumption). Generated from the
 * same resolved token map as strata.css so the utility layer can never
 * drift from the token source. `@theme inline` makes utilities reference
 * our runtime CSS variables (theme switching keeps working) without
 * re-emitting the variables themselves.
 */
import { serializeValue } from './css.js';
import { themeEntries, type ResolvedToken } from './tokens.js';

export function renderTailwindTheme(tokens: Map<string, ResolvedToken>): string {
  const lines: string[] = [];

  // Semantic tier → color/shadow utilities (bg-surface-base, text-text-primary, …).
  for (const [name, token] of themeEntries(tokens, 'light')) {
    if (token.value.kind === 'color') {
      lines.push(`  --color-${name}: var(--color-${name});`);
    } else if (token.value.kind === 'shadow') {
      lines.push(`  --${name}: var(--${name});`);
    }
  }

  for (const [path, token] of tokens) {
    if (path.startsWith('theme.')) continue;
    const segments = path.split('.');
    const value = token.value;
    if (path.startsWith('font.family.') && value.kind === 'fontFamily') {
      lines.push(`  --font-${segments[2] ?? ''}: var(--font-family-${segments[2] ?? ''});`);
    } else if (path.startsWith('font.size.') && value.kind === 'dimension') {
      lines.push(`  --text-${segments[2] ?? ''}: ${serializeValue(value)};`);
    } else if (path.startsWith('space.') && value.kind === 'dimension') {
      lines.push(`  --spacing-${segments[1] ?? ''}: ${serializeValue(value)};`);
    } else if (path.startsWith('radius.') && value.kind === 'dimension') {
      lines.push(`  --radius-${segments[1] ?? ''}: ${serializeValue(value)};`);
    } else if (path.startsWith('easing.') && value.kind === 'cubicBezier') {
      lines.push(`  --ease-${segments[1] ?? ''}: ${serializeValue(value)};`);
    }
  }

  return [
    '/* Strata → Tailwind v4 theme bridge — GENERATED by @drovano/tokens. Do not edit. */',
    '@theme inline {',
    ...lines,
    '}',
    '',
  ].join('\n');
}
